algoritmo "Area do trapezio"
// Função :executar a area de um trapezio
// Autor :Gabriel martins
// Data : 13/04/2026
// Seção de Declarações 
var
n1,n2,n3:real
valorFinal:real
inicio
// Seção de Comandos
 escreva ("Digite a base maior: ")
 leia(n1)
 escreva ("Digite a base menor: ")
 leia(n2)
   escreva ("Digite a altura: ")
   leia(n3)
//calculo
valorFinal <- (n1+n2)*n3/2
   limpatela
   escreva ("O valor da área é: ", valorFinal, "!")

fimalgoritmo
