algoritmo   "IMC"
// Função :Descubrir o IMC (Índice de Massa Corpórea)
// Autor :Gabriel martins
// Data : 13/04/2026
// Seção de Declarações 
var
n1,n2,n3:real
valorFinal:real
inicio
// Seção de Comandos
 escreva ("Digite o peso: ")
 leia(n1)
 escreva ("Digite a altura: ")
 leia(n2)
   escreva ("Digite a altura: ")
   leia(n3)
//calculo
valorFinal <- (n1+n2)*n3/2
   limpatela
   escreva ("O valor do IMC é: ", valorFinal, "!")

fimalgoritmo
