algoritmo   "IMC"
// Função :Área de um terreno retangular
// Autor :Gabriel martins
// Data : 13/04/2026
// Seção de Declarações 
var
n1,n2,n3:real
valorFinal:real
inicio
// Seção de Comandos
 escreva ("Digite a largura: ")
 leia(n1)
 escreva ("Digite o comprimento: ")
 leia(n2)
//calculo
valorFinal <- n1*n2
   limpatela
   escreva ("O valor da área é: ", valorFinal, "!")

fimalgoritmo
